# Generated by Django 6.0.2 on 2026-02-08 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('url_hash', models.CharField(db_index=True, help_text='SHA256 hash of URL for deduplication', max_length=64, unique=True)),
                ('canonical_url', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('language', models.CharField(blank=True, db_index=True, max_length=10)),
                ('sentiment_label', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], db_index=True, max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(db_index=True, default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_spam', models.BooleanField(db_index=True, default=False)),
                ('spam_signals', models.JSONField(blank=True, default=dict)),
                ('screenshot_path', models.CharField(blank=True, max_length=1024)),
                ('raw_html', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='clusters.cluster')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sources.source')),
            ],
            options={
                'db_table': 'articles_article',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['-fetched_at'], name='articles_ar_fetched_1d82d3_idx'), models.Index(fields=['source', '-fetched_at'], name='articles_ar_source__f56097_idx'), models.Index(fields=['language', '-fetched_at'], name='articles_ar_languag_1d77f7_idx'), models.Index(fields=['is_spam', 'quality_score', '-fetched_at'], name='articles_ar_is_spam_832861_idx')],
            },
        ),
    ]
