# Generated by Django 6.0.2 on 2026-02-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_created', models.IntegerField(default=0)),
                ('articles_duplicate', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'db_table': 'monitoring_scrapingjob',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='monitoring__source__11424c_idx'), models.Index(fields=['status', '-started_at'], name='monitoring__status_dcd283_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mention_count', models.IntegerField()),
                ('article_count', models.IntegerField()),
                ('velocity', models.FloatField(help_text='Rate of recent mentions vs total')),
                ('rank', models.IntegerField()),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
            ],
            options={
                'db_table': 'analytics_trendingtopic',
                'ordering': ['-date', 'rank'],
                'indexes': [models.Index(fields=['-date', 'rank'], name='analytics_t_date_fb4014_idx')],
                'unique_together': {('entity', 'date')},
            },
        ),
    ]
