# Generated by Django 6.0.2 on 2026-02-08 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.IntegerField(db_index=True)),
                ('summary', models.TextField(blank=True)),
                ('article_count', models.IntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('dominant_entities', models.JSONField(blank=True, default=list)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clusters_cluster',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['is_active', '-last_seen_at'], name='clusters_cl_is_acti_11d755_idx'), models.Index(fields=['is_trending', '-last_seen_at'], name='clusters_cl_is_tren_7b7ba4_idx'), models.Index(fields=['cluster_label'], name='clusters_cl_cluster_76e33e_idx')],
            },
        ),
    ]
