# Generated by Django 6.0.2 on 2026-02-08 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('ORG', 'Organization'), ('GPE', 'Geopolitical Entity'), ('LOC', 'Location'), ('PRODUCT', 'Product'), ('EVENT', 'Event'), ('DATE', 'Date'), ('MONEY', 'Money')], db_index=True, max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(db_index=True, help_text='Lowercased for matching', max_length=255)),
                ('mention_count', models.IntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entities_entity',
                'ordering': ['-mention_count'],
                'indexes': [models.Index(fields=['type', 'normalized_text'], name='entities_en_type_79f534_idx'), models.Index(fields=['-mention_count'], name='entities_en_mention_646028_idx')],
                'unique_together': {('type', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('extractor_name', models.CharField(default='spacy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='articles.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_mentions', to='entities.entity')),
            ],
            options={
                'db_table': 'entities_articleentity',
                'indexes': [models.Index(fields=['article'], name='entities_ar_article_1c636f_idx'), models.Index(fields=['entity'], name='entities_ar_entity__4d132f_idx')],
                'unique_together': {('article', 'entity', 'start_offset')},
            },
        ),
    ]
