# Generated by Django 6.0.2 on 2026-02-08 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('atom', 'Atom Feed'), ('html', 'HTML Scraping'), ('api', 'API'), ('telegram', 'Telegram Channel')], db_index=True, max_length=20)),
                ('feed_url', models.URLField(max_length=2048, unique=True)),
                ('base_url', models.URLField(max_length=1024)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_error', models.TextField(blank=True, default='')),
                ('trust_score', models.FloatField(default=0.5, help_text='0-1 score for source reliability', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_quality_score', models.FloatField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_keyword', models.CharField(blank=True, max_length=255)),
                ('auto_discovered', models.BooleanField(default=False)),
                ('poll_interval_minutes', models.IntegerField(default=30)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources_source',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enabled', '-last_polled_at'], name='sources_sou_enabled_18c132_idx'), models.Index(fields=['source_type', 'enabled'], name='sources_sou_source__932a1e_idx')],
            },
        ),
    ]
